=== cran/CornerstoneR/inst/variablesdialog/scriptvariables.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 sp1 (http://www.altova.com) by camLine (camLine GmbH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="variables">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:choice>
					<xs:element name="float">
						<xs:complexType>
							<xs:attribute name="name" type="xs:string" use="required"/>
							<xs:attribute name="label" type="xs:string" use="required"/>
							<xs:attribute name="min" type="xs:double" use="optional"/>
							<xs:attribute name="max" type="xs:double" use="optional"/>
							<xs:attribute name="default" type="xs:double" use="optional"/>
							<xs:attribute name="mandatory" type="xs:boolean" use="optional" default="false"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="integer">
						<xs:complexType>
							<xs:attribute name="name" type="xs:string" use="required"/>
							<xs:attribute name="label" type="xs:string" use="required"/>
							<xs:attribute name="min" type="xs:integer" use="optional"/>
							<xs:attribute name="max" type="xs:integer" use="optional"/>
							<xs:attribute name="default" type="xs:integer" use="optional"/>
							<xs:attribute name="mandatory" type="xs:boolean" use="optional" default="false"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="character">
						<xs:complexType>
							<xs:attribute name="name" type="xs:string" use="required"/>
							<xs:attribute name="label" type="xs:string" use="required"/>
							<xs:attribute name="default" type="xs:string" use="optional"/>
							<xs:attribute name="mandatory" type="xs:boolean" use="optional" default="false"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="logical">
						<xs:complexType>
							<xs:attribute name="name" type="xs:string" use="required"/>
							<xs:attribute name="label" type="xs:string" use="required"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="choice">
						<xs:complexType>
							<xs:attribute name="name" type="xs:string" use="required"/>
							<xs:attribute name="label" type="xs:string" use="required"/>
							<xs:attribute name="options" type="xs:string" use="required"/>
							<xs:attribute name="default" type="xs:string" use="optional"/>
							<xs:attribute name="mandatory" type="xs:boolean" use="optional" default="false"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="variable">
						<xs:complexType>
							<xs:attribute name="name" type="xs:string" use="required"/>
							<xs:attribute name="label" type="xs:string" use="required"/>
							<xs:attribute name="variables" type="xs:string" use="optional"/>
							<xs:attribute name="mandatory" type="xs:boolean" use="optional" default="false"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="formula">
						<xs:complexType>
							<xs:attribute name="name" type="xs:string" use="required"/>
							<xs:attribute name="label" type="xs:string" use="required"/>
							<xs:attribute name="variables" type="xs:string" use="optional"/>
							<xs:attribute name="mandatory" type="xs:boolean" use="optional" default="false"/>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cran/CornerstoneR/inst/variablesdialog/fitFunction.xml
<?xml version="1.0" encoding="UTF-8"?>
<variables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scriptvariables.xsd">
  <choice label = "Mathematical Function" name = "math.fun" options = "User Defined;Logistic" default = "User Defined" />
  <formula label = "Prediction Formula" name = "preds.frml" variables = "p" />
  <formula label = "Response Formula" name = "resp.frml" variables = "r" />
  <character label = "Limits" name = "limits" default = "min=NA, max=NA" />
  <character label = "Starting Values" name = "start.vals" />
  <variable label = "Weights" name = "weights" variables = "a" />
  <integer mandatory = "true" label = "Maximum Iterations" name = "max.iter" min = "1" default = "50"/>
  <float label = "Maximum Error in SS" name = "max.ftol" min = "0" default = "0" />
</variables>

=== cran/CornerstoneR/inst/tobedone/nls.xml
<?xml version="1.0" encoding="UTF-8"?>
<variables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scriptvariables.xsd">
 <variable label="Response" name="rsp" mandatory="true" variables="r"/>
 <choice label="Transformation" name="trn" options="none;log;square;inv;root;invroot;invsquare" default="none"/>
 <variable label="Weights" name="weights" variables="r,g,p"/>
 <formula label="Linear Terms" name="lin" variables="p"/>
 <formula label="Non-Linear Terms" name="nln" variables="p"/>
 <character label="Starting Values" name="start"/>
 <logical label="Trace" name="trc"/>
 <float label="Convergence Tolerance" name="tol" default="1e-5" min="1e-100" max="0.1" mandatory="true"/>
 <integer label="Max. Iterations" name="maxiter" min="1" default="50" mandatory="true"/>
</variables>
